from abc import ABC

from abc import abstractmethod


class LLMProvider(ABC):
    """
    Abstract base class for all
    Large Language Model providers.

    Any provider (Gemini, OpenAI,
    Ollama, Claude, etc.) must
    implement this interface.
    """

    @abstractmethod
    def generate(
        self,
        prompt: str
    ) -> str:
        """
        Generate a response from
        the given prompt.

        Parameters
        ----------
        prompt : str
            Prompt generated by the
            PromptBuilder.

        Returns
        -------
        str
            Generated explanation
            from the language model.
        """

        pass