import json

from typing import Dict


class PromptBuilder:
    """
    Builds a structured prompt
    for the Large Language Model.
    """

    def build_prompt(
        self,
        boot_analysis: Dict,
        anomaly_result: Dict
    ) -> str:
        """
        Build the prompt sent to
        the language model.

        Parameters
        ----------
        boot_analysis : Dict
            Structured boot analysis
            generated from the parser.

        anomaly_result : Dict
            Output generated by the
            Isolation Forest model.

        Returns
        -------
        str
            Complete prompt ready for
            the LLM.
        """

        prompt = f"""
You are an expert Embedded Linux Boot Engineer with extensive experience in Linux kernel boot, U-Boot, device drivers, memory management, root filesystem mounting, embedded hardware debugging, and boot failure analysis.

Your task is to analyze the structured boot information below.

The anomaly has already been detected by a Machine Learning model.

Your responsibility is NOT to classify the boot.

Instead, explain WHY the anomaly occurred using the available evidence.

==============================
BOOT ANALYSIS
==============================

{json.dumps(
    boot_analysis,
    indent=4
)}

==============================
ML ANALYSIS
==============================

{json.dumps(
    anomaly_result,
    indent=4
)}

==============================
Instructions
==============================

Based ONLY on the information above, provide:

1. Overall Boot Status

2. Boot Stage where failure occurred

3. Root Cause Analysis

4. Why the ML model likely detected this boot as anomalous

5. Severity
   (Low / Medium / High / Critical)

6. Supporting Evidence

7. Recommended Debugging Steps

8. Suggested Resolution

9. Short Technical Summary

Important Rules:

- Do NOT invent information.

- Do NOT assume missing values.

- Use only the supplied structured data.

- If information is insufficient, explicitly mention it.

Return the response in a professional technical report format.
"""

        return prompt