SEVERITY_KEYWORDS = {
        "ERROR": [
            "error",
            "failed",
            "failure",
            "panic",
            "unable",
            "denied",
            "exception",
            "segfault",
            "fault",
            "critical",
        ],
        "WARNING": [
            "warning",
            "warn",
            "not found",
            "deprecated",
            "retry",
            "timeout",
        ],
        "SUCCESS": [
            "boot successful",
            "mounted",
            "started",
            "registered",
            "link is up",
            "online",
            "initialized",
            "detected",
        ],
    }

SUBSYSTEM_KEYWORDS = {
    "UART": [
        "tty",
        "ttyama",
        "serial",
        "uart",
        "console",
    ],
    "NETWORK": [
        "eth",
        "network",
        "dhcp",
        # "lan",
        "ipv4",
        "ipv6",
        "eth0",
        "lan78xx",
        "ethernet",
        # "phy",
        # "dhcp",
        # "ipv4",
        # "ipv6",
        "tcp",
        "udp",
        "mac address",
        "link is up",
        "link is down",
        "network",
    ],
    "KERNEL": [
        "kaslr",
        "machine model",
        "efi",
        "numa",
        "node_data",
        "cpu:",
        "smp",
        "interrupt controller",
        "clocksource",
        "gic",
        "firmware",
        "command line",
        "scheduler",
        "rcu",
        "pid hash",
        "bogo",
        "calibrating delay",
        "irq",
        "acpi",
    ],



    "FILESYSTEM": [
        "ext4",
        "vfs",
        "filesystem",
        "mounted root",
        "mount",
        "rootfs",
        "mmcblk",
        "journal",
        # "filesystem",
        "superblock",

    ],
    "USB": [
        "usb",
        "keyboard",
        "mouse",
        "hub",
        "dwc_otg",
        "xhci",
        "ehci",
        "ohci",
        "usbcore",
        # "hub",
        "new usb device",
        "usb-storage",
    ],
    "MEMORY": [
        "memory",
        "ram",
        "dma",
        "cache",
        "reserved memory",
        "reserved mem",
        "cma",
        # "dma",
        "memory:",
        "memblock",
        "page allocator",
        "slab",
        "kmalloc",
        "vmalloc",
        "swap",
    ],
    "BOOT": [
        "boot",
        "init",
        "rcs",
        "/sbin/init",
    ],
}



